name: Reading notes test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - run: python -m pytest --cov --cov-report term-missing --cov-fail-under=100 --no-cov-on-fail
    - run: find . -type f -name "*.py" -not -path "./venv/*" -not -path "*/tests/*" | xargs pylint --fail-under 10
    - run: python -m isort . --check-only --verbose
